### ISSUE TITLE
RMLStreamer produces no output, no errors, no processing

### ISSUE THREAD

**Issue by sparkling** [RMLio/RMLStreamer#38]
```
>  pwd
/Users/blah/source/superpayments/data
> ls -al
total 2649984
drwxrwxrwx   5 blah  staff         160 17 May 21:52 .
drwxr-xr-x  13 blah  staff         416 17 May 21:56 ..
-rwxrwxrwx@  1 blah  staff  1356784150 17 May 13:19 datafeed_1025648.csv
-rwxrwxrwx   1 blah  staff         671 17 May 21:52 map.ttl
-rw-r--r--   1 blah  staff           0 17 May 21:52 output.nq
```

map.ttl:
```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.com/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .

@base <http://myorg.com/ns/> .

<TriplesMap1>
  a rr:TriplesMap;
        
  rml:logicalSource [ 
    rml:source "datafeed_1025648.csv";
    rml:referenceFormulation ql:CSV
  ] ;
	
  rr:subjectMap [ 
    rr:template "http://example.com/{aw_product_id}" 
  ]; 
	
  rr:predicateObjectMap [ 
    rr:predicate foaf:aw_deep_link ; 
    rr:objectMap [ 
      rml:reference "aw_deep_link" 
    ]
  ].
```

Works fine with the RMLMapper java app. When I send this command to the Flink cluster:
`toFile --mapping-file /mnt/data/map.ttl --output-path /mnt/data/output.nq
`
docker-compose.yml:
```

version: '3'
services:

  jobmanager:
    image: flink:1.14.0-scala_2.11-java11
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - /Users/blah/source/superpayments/data:/mnt/data

  taskmanager:
    image: flink:1.14.0-scala_2.11-java11
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - /Users/blah/source/superpayments/data:/mnt/data

volumes:
  # This volume will show with 'docker volume ls' as 'docker_data'
  data:

```

No errors are shown, no output is generated.

<img width="1478" alt="Screenshot 2022-05-17 at 22 01 38" src="https://user-images.githubusercontent.com/311648/168909528-a4fc58cc-6baf-4742-8566-833990671f3e.png">
